export const datos={
    album: [
        {
            label:"Titulo",
            responseName:"titulo",
            type:'string'
        },
        {
            label:"Nombres",
            responseName:"nombres",
            type:'string'
        },
        {
            label:"Upc",
            responseName:"upc",
            type:'string'
        },
        {
            label:"Total",
            responseName:"total",
            type:'currency'
        },
        {
            label:"Periodo",
            responseName:"periodo",
            type:'date'
        }
    ],
    pais:[
        {
            label:"Nombre",
            responseName:"nombre",
            type:'string'
        },
        {
            label:"Total",
            responseName:"total",
            type:'currency'
        },
        {
            label:"Periodo",
            responseName:"periodo",
            type:'date'
        }
    ],
    track:[
        {
            label:"Nombre",
            responseName:"nombre",
            type:'string'
        },
        {
            label:"Titulo",
            responseName:"titulo",
            type:'string'
        },
        {
            label:"Total",
            responseName:"total",
            type:'currency'
        },
        {
            label:"Periodo",
            responseName:"periodo",
            type:'date'
        }
    ],
    servicio:[
        {
            label:"Nombre",
            responseName:"nombre",
            type:'string'
        },
        {
            label:"Total",
            responseName:"total",
            type:'currency'
        },
        {
            label:"Periodo",
            responseName:"periodo",
            type:'date'
        }
    ],
    artista:[
        {
            label:"Nombres",
            responseName:"nombres",
            type:'string'
        },
        {
            label:"Total",
            responseName:"total",
            type:'currency'
        },
        {
            label:"Periodo",
            responseName:"periodo",
            type:'date'
        }
    ],
    sello:[
        {
            label:"Nombre",
            responseName:"sello",
            type:'string'
        },
        {
            label:"Total",
            responseName:"total",
            type:'currency'
        },
        {
            label:"Periodo",
            responseName:"periodo",
            type:'date'
        }
    ]

}

